### Send POST request with body as parameters
POST http://localhost:1337/user
Content-Type: application/x-www-form-urlencoded

username=daniel&password=daf332

###

POST http://localhost:1337/alojamiento
Content-Type: application/x-www-form-urlencoded

nombre=Casa&capacidad=4&garage=true&direccion=Esquina Perito Moreno y Calafate&imagenUrl=images/hogar.png&owner=1

